---
title: "Orignial Datasets"
author: "Fang Wang"
date: "2024-12-06"
output: html_document
---
#### 1.Recognized Shop Healthy Stores (20241116): Contains data on recognized healthy stores. Columns include store name, borough, street address, latitude, longitude, and year awarded.

#### 2. Farmers Market Data: Contains details about farmers' markets, such as market name, borough, address, latitude, longitude, and year.

#### 3. Retail Food Stores: Data on retail food stores, including entity name, street number, street name, borough, latitude, longitude, and other details.

#### 4. Food Pantry Data: Contains information about food pantries, including pantry names, borough, address, zip code, and latitude/longitude.

#### 5. Subway Dataset (subway.csv): Contains data on NYC subway station locations. Includes station coordinates (latitude and longitude) and potentially other descriptive information.

#### 6. Overweight Data by Borough (Overweight by boroughs.csv): Includes statistics on overweight percentages for each NYC borough, along with confidence intervals for the percentages and the year of measurement.